version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Run Tests
          command: premake5 test
      - run:
          name: Run Valgrind
          command: premake5 valgrind
