version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Tools
          command: apt-get -y update && apt-get install -y wget make g++ dh-autoreconf pkg-config valgrind tar
      - run:
          name: Install premake
          command: wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-linux.tar.gz && \
                   whereis tar && \
                   yum -y install tar && \
                   tar -zxvf premake-*.tar.gz && \
                   rm premake-*.tar.gz && \
                   mv premake5 /usr/local/bin
      - run:
          name: Build CMake Images
          command: find . -exec touch {} \; && premake5 gmake && make -j32 test && cp ./bin/* /app
      - run:
          name: Run Tests
          command: premake5 test

      - run:
          name: Run Valgrind
          command: premake5 valgrind
